### ISSUE TITLE
Implement FATE tool calculations

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/cp_nigeria_app#15]
Some cells of the FATE tool spreadsheet should be programmatically modified and the output fetched.

The file is in static and is copied and the "input cells" are filled via json
(The file is ready to be downloaded by the user upon button click) (only if the FATE tool is open)
We fetch some values of the file and send them back (via json) to the result page where we display them

json structure:
```
json = {
"capital_costs": {"cell ref": "C12", "value": 12.3 "verbose": "Capital Costs", }
}

cell_ref, verbose,value,name,
C12,Capital Costs,12.3,capital_costs,


json["capital_costs"]["value"] = here write how to get this value from what the user inputed

Consumer.Type.gather_fate_inputs(json, list_of_var_names)

for loop with 
json[<var_name>]["value"]  = gettattr(self, <var_name>)



write methods on the models to autofill the json when there is a lot of cells to be filled from a model instance 

```

**Comment by Bachibouzouk** [comment]
Thanks

**Comment by paulapreuss** [comment]
Update: FATE excel tool has now been replaced by a "Financial Tool" excel. To avoid the back and forth between tool and excel sheets and complications coming from that, it is being directly implemented in python instead. #88 will close this issue once and for all (hopefully).
