### ISSUE TITLE
Improve view 2 -  demand load profile generation

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/cp_nigeria_app#3]
Have dummy actual timeseries to see a combined graph with the result being updated live.

*open question* should this graph be above the others, should it appear only after the first usergroup is filled?

Each household group should be a model in the DB and displayed in a div where one can delete them --> similar to ReportItem in the dashboard result.

There should only be one button "add household group" and one can add as many as wished.
*open question*: what is the strategy to display more than say 5 household group (e.g. overflow with max 3 per line?)

**Comment by paulapreuss** [comment]
Check out queryset and ForeignKey 

JavaScript code für neue divs

**Comment by Bachibouzouk** [comment]
grid_model_topology.js line 290
