### ISSUE TITLE
Automatically generate implementation plan from outputs

### ISSUE THREAD

**Issue by paulapreuss** [rl-institut/cp_nigeria_app#60]
- The implementation plan should be a word report including relevant output tables and figues as well as some text blocks depending on community characteristics, chosen business model etc.
- This implementation plan should include all information needed for a community to initiate next steps, e.g. approach a DisCo or a project planner
- The different texts to be input are still tbd
- The word report will look something like this: https://docs.google.com/document/d/1x0XpJjFjxbDPbfqC28-I4tBcKyaCBPI61BnqXr2pwp8/edit?pli=1#heading=h.x44w4d49ch82

**Comment by Bachibouzouk** [comment]
Upon graph generation on the output page, png should be saved in the cache and get upon report download

**Comment by Bachibouzouk** [comment]
`base64.b64encode(fig2.to_image(format="png", height=500, width=900)).decode()` Can be used to encode the image files in the cache (suggestion, maybe there are better solutions)

**Comment by paulapreuss** [comment]
> Upon graph generation on the output page, png should be saved in the cache and get upon report download

see for further reading https://docs.djangoproject.com/en/5.0/topics/http/sessions/

**Comment by Bachibouzouk** [comment]
To write the text with variable values in it:
```
>>> s = "eieiejd {param2}"
>>> s.format(**dict(param2=23))
'eieiejd 23'
>>> s.format(param2=12)
'eieiejd 12'
```

The tables can be added, but the caption automatic numbering might be an issue (user must click alt+F9) when opening the file the first time after download, which is ok

The graphics will be described by GW colleagues
