### ISSUE TITLE
Improve view 2 GUI

### ISSUE THREAD

**Issue by paulapreuss** [rl-institut/cp_nigeria_app#7]
Instead of just households, users should be able to select between different user types (households, enterprises, public facilities, ...). Instead of "load curve", the user should then select "type of facility" from a drop down (that will later ideally provide standardized load curves).

**Comment by paulapreuss** [comment]
- [ ] Change user to consumer
- [ ] Display aggregated load profile at the bottom
- [ ] Add upload load profile button at the top
- [ ] Show most important demand figures -> total daily demand, daily peak demand

**Comment by paulapreuss** [comment]
@Bachibouzouk 
If each enterprise/facility has its own div, the screen will eventually get really full with the current idea of adding divs as needed (if a community has 10+ enterprises, household groups and also facilities). 

Would it maybe be better to have one div/form for households, one for enterprises and one for facilities (always three divs in total), where a user can somehow input all enterprises needed and directly generate an aggreated load? Something like this:
Enterprises:
- [ ] Supermarket, amount:
- [ ] Restaurant, amount:
- [ ] Kiosk, amount: 

etc...

**Comment by Bachibouzouk** [comment]
This issue was solved by #19
