### ISSUE TITLE
Make demand timeseries shorter (week window) for the demand graph feedback

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/cp_nigeria_app#79]
As the user does only see one week, there is no need to transfer the full timeseries. That way slow connexion will suffer less and we can keep the disagreggated timeseries view (for the communites the demand was just an aggregated profile, the information of which consumer contributes to the demand the most being lost in the process)

**Comment by paulapreuss** [comment]
Fix while doing this: KPIs not updating when consumer group is deleted
