### ISSUE TITLE
Set a global variable for "exchange rate" and have all default costs be in USD

### ISSUE THREAD

**Issue by paulapreuss** [rl-institut/cp_nigeria_app#87]
This would be cleaner since the default costs we assume all come from USD assumptions. The USD costs can then be multiplied by whatever exchange rate is set. This would allow for the exchange rate to be easily adapted if heavy fluctuation ocurrs and also allow the user to start a project in USD instead of NGN and still have appropriate default values.

**Comment by paulapreuss** [comment]
Technically, this would even allow for an "advanced option" to adapt the current exchange rate while still keeping our default values

**Comment by Bachibouzouk** [comment]
Agreed, it would make sense as the exchange rate changes quite a lot these times. We can add it to cp_nigeria/models.py::Options

**Comment by Bachibouzouk** [comment]
The user should be able to change it
